#include <iostream>
using namespace std;
// int main()
// {
//     int a = 10;
//     int b = 10;
//     int c = a + b;
//     int d = a * b;
//     float e = a % b;
//     cout << "The sum of a and b is " << c << endl;
//     cout << "The multiple  of a and b is " << d << endl;
//     cout << "The divide of a and b is " << e << endl;

//     return 0;
// }

int main()
{
    for (int i = 1; i < 5; i++)
    {
        for (int j = 0; j <= 5; j++)
        {
            cout << "#";
        }
        cout << endl;
    }

    return 0;
}
// --------------------------OutPut----------------------------------
// ######
// ######
// ######
// ######